/**
 * Generate golden vectors for the PRNG to pin the wire format.
 * This script should be run once to create test/fixtures/vectors.json.
 *
 * The vectors pin:
 * - packetSeed() output for known inputs
 * - deriveIndices() output for known inputs
 * - splitmix32() sequence for a known seed
 *
 * Any change to the PRNG that changes these outputs is a wire-breaking change.
 */

import { writeFile, mkdir } from 'fs/promises';
import { dirname } from 'path';
import { deriveIndices, makeDegreeTable, packetSeed, splitmix32 } from '../src/core/fountain/prng.js';
import { DEGREE_CAP, K } from '../src/core/params.js';

const vectors = {
  description: 'Golden vectors for PRNG wire format (I3). Generated by ScreenFerry implementation.',
  version: 1,
  generated: new Date().toISOString(),
  vectors: []
};

// Test packetSeed with various inputs
const packetSeedCases = [
  { streamId: 0xdeadbeef, blockIndex: 0, seq: 0 },
  { streamId: 0xdeadbeef, blockIndex: 3, seq: 42 },
  { streamId: 0, blockIndex: 0, seq: 0 },
  { streamId: 0xffffffff, blockIndex: 0xffffff, seq: 0xffffff },
  { streamId: 0x80000000, blockIndex: 1, seq: 0x7fffff },
];

for (const c of packetSeedCases) {
  vectors.vectors.push({
    type: 'packetSeed',
    input: c,
    output: packetSeed(c.streamId, c.blockIndex, c.seq)
  });
}

// Test splitmix32 sequence
const seedCases = [0xdeadbeef, 0, 0xffffffff, 12345];
for (const seed of seedCases) {
  const rnd = splitmix32(seed);
  const sequence = [];
  for (let i = 0; i < 10; i++) {
    sequence.push(rnd());
  }
  vectors.vectors.push({
    type: 'splitmix32',
    input: { seed },
    output: sequence
  });
}

// Test deriveIndices with various inputs
const degreeTable = makeDegreeTable(K, DEGREE_CAP);
const deriveIndicesCases = [
  { streamId: 0xdeadbeef, blockIndex: 0, seq: 0 },
  { streamId: 0xdeadbeef, blockIndex: 3, seq: 42 },
  { streamId: 0xabcdef, blockIndex: 0, seq: 0 },
  { streamId: 0xabcdef, blockIndex: 0, seq: 1 },
  { streamId: 0xabcdef, blockIndex: 0, seq: 2 },
];

for (const c of deriveIndicesCases) {
  const indices = deriveIndices(c.streamId, c.blockIndex, c.seq, K, degreeTable);
  vectors.vectors.push({
    type: 'deriveIndices',
    input: { ...c, k: K, degreeCap: DEGREE_CAP },
    output: Array.from(indices)
  });
}

// Test makeDegreeTable
const degreeTableOutput = Array.from(degreeTable);
vectors.vectors.push({
  type: 'makeDegreeTable',
  input: { k: K, cap: DEGREE_CAP },
  output: degreeTableOutput
});

// Write to file
const dir = dirname('test/fixtures/vectors.json');
await mkdir(dir, { recursive: true });
await writeFile('test/fixtures/vectors.json', JSON.stringify(vectors, null, 2));
console.log('Generated test/fixtures/vectors.json');
